name: explosig-server-dev-env
channels:
  - conda-forge
  - omnia
dependencies:
  - python>=3.7
  - anaconda
  - uvicorn
  - starlette
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - quadprog==0.1.6
  - fastparquet==0.2.1
  - jsonschema==2.6.0
  - SQLAlchemy==1.2.15
  - mysqlclient==1.3.14
  - argon2_cffi==19.1.0
  - requests